version: "1.0"
info:
  model: int-scaffold
packages:
- name: March12Project
  gitServerName: march12shshi
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
